apiVersion: v1
kind: Service
metadata:
  name: contoso-pizza-svc
  labels:
    app: contoso-pizza
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: contoso-pizza
